### ISSUE TITLE
Quest: Curriculum and Preprocessing for Translation Targets

### ISSUE THREAD

**Issue by gkielian** [ReaLLMASIC/ReaLLM-Forge#129]
This would start with pretraining on multilingual corpus, comparing phonemization with regular tiktoken.

- [ ] phonemization and train/val.bin with pre-training datasets
- [ ] phonemization and train/val.bin with of fine-tuning
- [ ] tiktoken of train/val.bin
- [ ] tiktoken of fine-tuning

For now let us target English <-> Japanese language training pairs.
